//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace SqlServerHelper.Entity {

	[JsonObject(MemberSerialization.OptIn)]
	[Table(Name ="Account")]
	public partial class DboAccount {

		[JsonProperty, Column(DbType = "char(20)",Name = "Account")]
		public string Account { get; set; }

		[JsonProperty, Column(DbType = "binary(942)")]
		public byte[] Beast { get; set; }

		[JsonProperty, Column(Name = "BeastMaxNum")]
		public int Beastmaxnum { get; set; }

		[JsonProperty, Column(Name = "BonusID1")]
		public long? Bonusid1 { get; set; }

		[JsonProperty, Column(Name = "BonusID2")]
		public long? Bonusid2 { get; set; }

		[JsonProperty, Column(Name = "BonusID3")]
		public long? Bonusid3 { get; set; }

		[JsonProperty, Column(Name = "BonusID4")]
		public long? Bonusid4 { get; set; }

		[JsonProperty, Column(Name = "dw64Dword1")]
		public long Dw64dword1 { get; set; }

		[JsonProperty, Column(Name = "dw64Dword2")]
		public long Dw64dword2 { get; set; }

		[JsonProperty, Column(Name = "dw64Dword3")]
		public long Dw64dword3 { get; set; }

		[JsonProperty, Column(Name = "dw64Dword4")]
		public long Dw64dword4 { get; set; }

		[JsonProperty, Column(Name = "dwDword1")]
		public int Dwdword1 { get; set; }

		[JsonProperty, Column(Name = "dwDword2")]
		public int Dwdword2 { get; set; }

		[JsonProperty, Column(Name = "dwDword3")]
		public int Dwdword3 { get; set; }

		[JsonProperty, Column(Name = "dwDword4")]
		public int Dwdword4 { get; set; }

		[JsonProperty, Column(Name = "ECommodity", DbType = "binary(864)")]
		public byte[] Ecommodity { get; set; }

		[JsonProperty, Column(DbType = "binary(3072)")]
		public byte[] Equip { get; set; }

		[JsonProperty, Column(Name = "GameID")]
		public short Gameid { get; set; }

		[JsonProperty, Column(Name = "GoodsFlag")]
		public short Goodsflag { get; set; }

		[JsonProperty, Column(Name = "ID1")]
		public long? Id1 { get; set; }

		[JsonProperty, Column(Name = "ID2")]
		public long? Id2 { get; set; }

		[JsonProperty, Column(Name = "ID3")]
		public long? Id3 { get; set; }

		[JsonProperty, Column(Name = "idlastonline")]
		public long? Idlastonline { get; set; }

		[JsonProperty, Column(Name = "IsLock")]
		public byte Islock { get; set; }

		[JsonProperty, Column(Name = "LastTimeInGame")]
		public DateTime? Lasttimeingame { get; set; }

		[JsonProperty, Column(Name = "LastTimeOutGame")]
		public DateTime? Lasttimeoutgame { get; set; }

		[JsonProperty, Column(Name = "MakeMethod", DbType = "binary(1152)")]
		public byte[] Makemethod { get; set; }

		[JsonProperty, Column(DbType = "binary(1152)")]
		public byte[] Material { get; set; }

		[JsonProperty]
		public int Money { get; set; }

		[JsonProperty]
		public int Point { get; set; }

		[JsonProperty, Column(DbType = "char(16)")]
		public string String { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
