//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace SqlServerHelper.Entity {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Auction {

		[JsonProperty, Column(DbType = "char(20)")]
		public string Account { get; set; }

		[JsonProperty, Column(Name = "AuctionID")]
		public long Auctionid { get; set; }

		[JsonProperty, Column(Name = "AuctionMoney")]
		public int Auctionmoney { get; set; }

		[JsonProperty, Column(Name = "AuctionPointCard")]
		public int Auctionpointcard { get; set; }

		[JsonProperty, Column(Name = "BuyAuctionID")]
		public long Buyauctionid { get; set; }

		[JsonProperty, Column(Name = "GameID")]
		public short Gameid { get; set; }

		[JsonProperty, Column(Name = "GoodsType")]
		public byte Goodstype { get; set; }

		[JsonProperty, Column(Name = "ID")]
		public long Id { get; set; }

		[JsonProperty, Column(Name = "MixGoods", DbType = "binary(200)")]
		public byte[] Mixgoods { get; set; }

		[JsonProperty]
		public int Money { get; set; }

		[JsonProperty, Column(Name = "PointCard")]
		public int Pointcard { get; set; }

		[JsonProperty, Column(Name = "RemainedTime")]
		public long Remainedtime { get; set; }

		[JsonProperty, Column(Name = "s", DbType = "char(128)")]
		public string S { get; set; }

		[JsonProperty]
		public short State { get; set; }

		[JsonProperty]
		public int Time { get; set; }

		[JsonProperty]
		public short Type { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
