//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace SqlServerHelper.Entity {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class Faction {

		[JsonProperty, Column(Name = "BitMap", DbType = "binary(4096)")]
		public byte[] Bitmap { get; set; }

		[JsonProperty, Column(DbType = "binary(360)")]
		public byte[] Building { get; set; }

		[JsonProperty]
		public short Count { get; set; }

		[JsonProperty]
		public int Earth { get; set; }

		[JsonProperty, Column(Name = "EnemyFactionID")]
		public int Enemyfactionid { get; set; }

		[JsonProperty, Column(Name = "FactionBBeast", DbType = "binary(628)")]
		public byte[] Factionbbeast { get; set; }

		[JsonProperty, Column(Name = "FactionID")]
		public int Factionid { get; set; }

		[JsonProperty, Column(Name = "FactionMaster")]
		public long Factionmaster { get; set; }

		[JsonProperty, Column(Name = "FactionName", DbType = "char(16)")]
		public string Factionname { get; set; }

		[JsonProperty, Column(Name = "FriendFactionID1")]
		public int Friendfactionid1 { get; set; }

		[JsonProperty, Column(Name = "FriendFactionID2")]
		public int Friendfactionid2 { get; set; }

		[JsonProperty]
		public int Furry { get; set; }

		[JsonProperty]
		public int God { get; set; }

		[JsonProperty]
		public int Honor { get; set; }

		[JsonProperty]
		public int Human { get; set; }

		[JsonProperty, Column(DbType = "char(512)")]
		public string Inform { get; set; }

		[JsonProperty]
		public int Killed { get; set; }

		[JsonProperty]
		public short Level { get; set; }

		[JsonProperty]
		public int Liquid { get; set; }

		[JsonProperty]
		public int Lively { get; set; }

		[JsonProperty, Column(Name = "MasterName", DbType = "char(12)")]
		public string Mastername { get; set; }

		[JsonProperty]
		public int Medicine { get; set; }

		[JsonProperty]
		public int Mineral { get; set; }

		[JsonProperty]
		public int Money { get; set; }

		[JsonProperty]
		public int Monster { get; set; }

		[JsonProperty]
		public int Sky { get; set; }

		[JsonProperty]
		public int Stone { get; set; }

		[JsonProperty, Column(Name = "XuanYan", DbType = "char(512)")]
		public string Xuanyan { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
