//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace SqlServerHelper.Entity {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "UserDB")]
	public partial class Userdb {

		[JsonProperty, Column(Name = "AbnormalBeastID")]
		public int Abnormalbeastid { get; set; }

		[JsonProperty, Column(DbType = "char(20)")]
		public string Account { get; set; }

		[JsonProperty, Column(Name = "ActionDirection")]
		public byte Actiondirection { get; set; }

		[JsonProperty, Column(Name = "AddMaterialIndex1")]
		public short Addmaterialindex1 { get; set; }

		[JsonProperty, Column(Name = "AddMaterialIndex2")]
		public short Addmaterialindex2 { get; set; }

		[JsonProperty, Column(Name = "AliasIndex")]
		public byte Aliasindex { get; set; }

		[JsonProperty]
		public byte Anger { get; set; }

		[JsonProperty, Column(Name = "AttributePoint")]
		public byte Attributepoint { get; set; }

		[JsonProperty, Column(Name = "AutoAttackNum")]
		public int Autoattacknum { get; set; }

		[JsonProperty, Column(Name = "BattleType")]
		public short Battletype { get; set; }

		[JsonProperty, Column(Name = "BBeastIndex")]
		public int Bbeastindex { get; set; }

		[JsonProperty, Column(Name = "bBYTE", DbType = "binary(8)")]
		public byte[] Bbyte { get; set; }

		[JsonProperty, Column(DbType = "binary(942)")]
		public byte[] Beast { get; set; }

		[JsonProperty, Column(Name = "BodyMaterial", DbType = "binary(48)")]
		public byte[] Bodymaterial { get; set; }

		[JsonProperty, Column(Name = "BornSceneID")]
		public int Bornsceneid { get; set; }

		[JsonProperty]
		public int Cloud { get; set; }

		[JsonProperty, Column(Name = "CloudColor")]
		public int Cloudcolor { get; set; }

		[JsonProperty, Column(Name = "ConfTaskNum", DbType = "binary(20)")]
		public byte[] Conftasknum { get; set; }

		[JsonProperty, Column(DbType = "binary(16)")]
		public byte[] Consort { get; set; }

		[JsonProperty]
		public short Courage { get; set; }

		[JsonProperty, Column(Name = "CurrentPoint")]
		public int Currentpoint { get; set; }

		[JsonProperty, Column(Name = "date")]
		public int Date { get; set; }

		[JsonProperty, Column(Name = "dongjiedblexptime")]
		public byte? Dongjiedblexptime { get; set; }

		[JsonProperty, Column(Name = "dwDWORD", DbType = "binary(32)")]
		public byte[] Dwdword { get; set; }

		[JsonProperty, Column(Name = "dwDWORD64", DbType = "binary(32)")]
		public byte[] Dwdword64 { get; set; }

		[JsonProperty, Column(DbType = "binary(1248)")]
		public byte[] Equip { get; set; }

		[JsonProperty, Column(Name = "EquipLock", DbType = "char(16)")]
		public string Equiplock { get; set; }

		[JsonProperty, Column(Name = "ESkill", DbType = "binary(320)")]
		public byte[] Eskill { get; set; }

		[JsonProperty]
		public int Experience { get; set; }

		[JsonProperty, Column(Name = "FactionID")]
		public int Factionid { get; set; }

		[JsonProperty]
		public int Family { get; set; }

		[JsonProperty]
		public short Fortune { get; set; }

		[JsonProperty, Column(DbType = "binary(640)")]
		public byte[] Friend { get; set; }

		[JsonProperty, Column(Name = "GodID")]
		public int Godid { get; set; }

		[JsonProperty, Column(Name = "GodLastTime")]
		public int Godlasttime { get; set; }

		[JsonProperty, Column(Name = "GoodEvil")]
		public short Goodevil { get; set; }

		[JsonProperty, Column(Name = "HairColor")]
		public int Haircolor { get; set; }

		[JsonProperty, Column(Name = "HairID")]
		public int Hairid { get; set; }

		[JsonProperty, Column(Name = "HeadID")]
		public int Headid { get; set; }

		[JsonProperty]
		public int Hp { get; set; }

		[JsonProperty, Column(Name = "ID")]
		public long Id { get; set; }

		[JsonProperty, Column(Name = "ISkill", DbType = "binary(800)")]
		public byte[] Iskill { get; set; }

		[JsonProperty]
		public byte Level { get; set; }

		[JsonProperty, Column(Name = "LevelTaskID")]
		public long Leveltaskid { get; set; }

		[JsonProperty, Column(Name = "MakeGrimace")]
		public byte Makegrimace { get; set; }

		[JsonProperty, Column(Name = "MapTaskID")]
		public long Maptaskid { get; set; }

		[JsonProperty, Column(Name = "MaxBBeastCount")]
		public byte Maxbbeastcount { get; set; }

		[JsonProperty]
		public byte Mind { get; set; }

		[JsonProperty]
		public int Money { get; set; }

		[JsonProperty, Column(Name = "MostlyTaskID")]
		public long Mostlytaskid { get; set; }

		[JsonProperty]
		public int Mp { get; set; }

		[JsonProperty, Column(DbType = "char(12)")]
		public string Name { get; set; }

		[JsonProperty, Column(Name = "OfficialAlias")]
		public short Officialalias { get; set; }

		[JsonProperty, Column(DbType = "binary(200)")]
		public byte[] Pet { get; set; }

		[JsonProperty, Column(Name = "PForce")]
		public short Pforce { get; set; }

		[JsonProperty, Column(DbType = "binary(128)")]
		public byte[] Prop { get; set; }

		[JsonProperty, Column(Name = "ProtectBeast")]
		public int Protectbeast { get; set; }

		[JsonProperty, Column(Name = "PSkill", DbType = "binary(640)")]
		public byte[] Pskill { get; set; }

		[JsonProperty, Column(Name = "PSkillNum")]
		public int Pskillnum { get; set; }

		[JsonProperty, Column(Name = "ReliveSceneID")]
		public int Relivesceneid { get; set; }

		[JsonProperty, Column(Name = "ReliveX")]
		public short Relivex { get; set; }

		[JsonProperty, Column(Name = "ReliveY")]
		public short Relivey { get; set; }

		[JsonProperty, Column(Name = "restdblexptime")]
		public short? Restdblexptime { get; set; }

		[JsonProperty, Column(Name = "RoleTaskID")]
		public long Roletaskid { get; set; }

		[JsonProperty, Column(Name = "SceneID")]
		public int Sceneid { get; set; }

		[JsonProperty, Column(Name = "SecondaryTaskIndex", DbType = "binary(128)")]
		public byte[] Secondarytaskindex { get; set; }

		[JsonProperty, Column(Name = "SelfAlias", DbType = "char(12)")]
		public string Selfalias { get; set; }

		[JsonProperty, Column(Name = "ShortCut", DbType = "binary(48)")]
		public byte[] Shortcut { get; set; }

		[JsonProperty, Column(Name = "ShortCutPage")]
		public byte Shortcutpage { get; set; }

		[JsonProperty, Column(DbType = "binary(120)")]
		public byte[] State { get; set; }

		[JsonProperty, Column(Name = "TailStripColor")]
		public int Tailstripcolor { get; set; }

		[JsonProperty, Column(DbType = "binary(1280)")]
		public byte[] Task { get; set; }

		[JsonProperty, Column(Name = "TAttribute", DbType = "binary(8)")]
		public byte[] Tattribute { get; set; }

		[JsonProperty]
		public byte Transfer { get; set; }

		[JsonProperty]
		public byte Type { get; set; }

		[JsonProperty, Column(Name = "wWORD", DbType = "binary(16)")]
		public byte[] Wword { get; set; }

		[JsonProperty, Column(Name = "YQSCaiFuZhi")]
		public int Yqscaifuzhi { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
