//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace MySqlHelper.Entity {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class t_consume {

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string account { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(20)")]
		public string arerid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(16)")]
		public string ip { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "int(4)")]
		public int? itemid { get; set; }

		[JsonProperty, Column(DbType = "int(4)")]
		public int? num { get; set; }

		[JsonProperty, Column(DbType = "int(4)")]
		public int? price { get; set; }

		[JsonProperty, Column(DbType = "int(4)")]
		public int? serverid { get; set; }

		[JsonProperty, Column(DbType = "int(4)")]
		public int? status { get; set; }

		[JsonProperty, Column(DbType = "int(4) unsigned")]
		public uint? time { get; set; }

		[JsonProperty, Column(DbType = "int(4)")]
		public int? totalprice { get; set; }

	}

}
