//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace MySqlHelper.Entity {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class t_xntg {

		/// <summary>
		/// pw_username
		/// </summary>
		[JsonProperty, Column(DbType = "char(20)", IsPrimary = true)]
		public string passport_id { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "char(255)")]
		public string baohu { get; set; } = string.Empty;

		/// <summary>
		/// ????
		/// </summary>
		[JsonProperty, Column(DbType = "tinyint(1) unsigned")]
		public byte memberlevel { get; set; }

		[JsonProperty, Column(DbType = "int(6)")]
		public int? mobi { get; set; }

		[JsonProperty, Column(DbType = "char(20)")]
		public string passport_cardid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "tinyint(1) unsigned")]
		public byte passport_isold { get; set; }

		[JsonProperty, Column(DbType = "smallint(2) unsigned")]
		public ushort passport_prized_20_num { get; set; }

		[JsonProperty, Column(DbType = "smallint(2)")]
		public short passport_prized_40_num { get; set; }

		[JsonProperty, Column(DbType = "char(32)")]
		public string passport_pwd { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "char(20)")]
		public string passport_regtime { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "smallint(2) unsigned")]
		public ushort passport_sp_20_num { get; set; }

		[JsonProperty, Column(DbType = "smallint(2) unsigned")]
		public ushort passport_sp_40_num { get; set; }

		[JsonProperty, Column(DbType = "tinyint(1) unsigned")]
		public byte passport_sp_ok { get; set; }

		[JsonProperty, Column(DbType = "char(20)")]
		public string passport_spreader { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "char(20)")]
		public string passport_spreaderseail { get; set; } = string.Empty;

		/// <summary>
		/// ???????????
		/// </summary>
		[JsonProperty, Column(DbType = "int(4) unsigned")]
		public uint usedsign { get; set; }

		[JsonProperty, Column(DbType = "char(100)")]
		public string xntg_hasbonus { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "char(16)")]
		public string xntg_logip { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "tinyint(1) unsigned")]
		public byte xntg_maxrolelv { get; set; }

		[JsonProperty, Column(DbType = "tinyint(1) unsigned")]
		public byte xntg_prizedmaxlv { get; set; }

		[JsonProperty, Column(DbType = "int(4)")]
		public int xntg_tianbaopoint { get; set; }

	}

}
